heat_template_version: 2016-10-14

parameters: 
  image:
    type: string
  count:
    type: string
    default: 2
  public_network:
    type: string
    default: public-net
  whitelist_ip:
    type: string
    default: 202.78.240.7

resources:

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: public_network}

  network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          port_range_min: 0
          port_range_max: 65535
          remote_ip_prefix: 
            list_join: ["/", [{get_param: whitelist_ip},"32"]]
        - protocol: udp
          port_range_min: 0
          port_range_max: 65535
          remote_ip_prefix: 
            list_join: ["/", [{get_param: whitelist_ip},"32"]]

  resource_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: count }
      resource_def:
        type: OS::LB::Server
        properties:
          index: "%index%"
          network: { get_resource: network }
          security_group: { get_resource: security_group }
          image: { get_param: image }
          router: { get_resource: router }
          whitelist_ip: { get_param: whitelist_ip }
          public_network: { get_param: public_network }
